### ISSUE TITLE
pyobis example notebook using known dataset ids

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos_code_lab#106]
- [ ] What is language(s) for used in the example?
   - Python
- [ ] Is it focused on a particular module/software or an IOOS data service?
   - pyobis
- [ ] Can you provide a minimum example of the expected code and results in a notebook?
   - https://github.com/MathewBiddle/sandbox/blob/main/notebooks/IOOS_occurrences_in_OBIS.ipynb

Please provide a detailed description of the suggested example below:
The example notebook, provided above, uses two google spreadsheets (which contain OBIS dataset IDs affiliated with various IOOS efforts) to collect occurrence observations in OBIS. I would like to make a notebook that does the same thing, but uses the pyobis package to gather data. 

Maybe we can think of a more logical way to manage the dataset IDs too? I don't think we can do searches in OBIS for related keywords, but could be possible?

It would like to see a heatmap of where affiliated IOOS networks have contributed occurrence observations.

**Comment by MathewBiddle** [comment]
Create a map and histograms similar to what is done in this notebook

https://github.com/ayushanand18/pyobis/blob/bio-mapping/notebooks/biodiversity_mapping.ipynb

**Comment by ocefpaf** [comment]
@MathewBiddle the link above was from a branch that no longer exists. Here is a permalink for future reference: https://github.com/ayushanand18/pyobis/blob/5907b0f37a26600f4945dfc217a8894bea6d9349/notebooks/biodiversity_mapping.ipynb

**Comment by MathewBiddle** [comment]
Figured out how to manage a list of known dataset IDs. Once the issue below is closed we should be able to search for datasets associated with US MBON using pyobis:
* https://github.com/ioos/mbon-docs/issues/19

US MBON institution record in OBIS: https://obis.org/institute/23070
