### ISSUE TITLE
GHAction run-tests failing

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos_code_lab#117]
Looks like the interpolate ERDDAP notebook is failing during the run-tests, Notebook tests:

https://github.com/ioos/ioos_code_lab/actions/runs/3549906453/jobs/5962786926

`data_analysis_and_visualization_notebooks/2021-10-25-ERDDAP-interpolate.ipynb`

**Comment by ocefpaf** [comment]
It is a 403, Bob probably locked us out again. We need to change the server we are using for that example.

**Comment by ocefpaf** [comment]
We are not locked out yet, so restarting does the trick. I also fixed as many tests as I could in #130. If this one keeps returning 403 we have only two options:

1. add it to the 'don't run' list
2. get a similar dataset into the ioos sensor ERDDAP to workaround the server limitations

For now I think we can close this one.
