### ISSUE TITLE
Add "star

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/ioos_code_lab#140]
For windows, after installing minimamba, there should be instructions:
* click the window start button and browse to the "miniforge3" folder
* drag "miniforge prompt" onto your windows taskbar (the bar with the icons at the bottom of your screen)
* start the miniforge prompt by clicking on the miniforge prompt icon on your windows taskbar

**Comment by rsignell-usgs** [comment]
Oh, I guess these instructions are there -- but they seem in the wrong place?  Shouldn't they be earlier?

**Comment by ocefpaf** [comment]
> Oh, I guess these instructions are there -- but they seem in the wrong place? Shouldn't they be earlier?

To be honest I'm not sure. I only use Windows to create those instructions so feedback from Windows user is very welcomed. 

What do you think? Should we move them?
