### ISSUE TITLE
Issue on page /content/intro.html

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos_code_lab#191]
Add a link to the contributing guide to the home page. Can we make some flashy button or something that links to https://github.com/ioos/ioos_code_lab/blob/main/CONTRIBUTING.md ?

```
<button name="button" onclick="https://github.com/ioos/ioos_code_lab/blob/main/CONTRIBUTING.md">Contribute here!</button>
```

**Comment by ocefpaf** [comment]
I'll try this tomorrow and mint a release after we implement it. What do you think?

**Comment by MathewBiddle** [comment]
Sounds good!

**Comment by MathewBiddle** [comment]
probably update https://ioos.github.io/ioos_code_lab/content/contact_us.html too?

**Comment by ocefpaf** [comment]
> probably update https://ioos.github.io/ioos_code_lab/content/contact_us.html too?

What are you planning on adding here? I confess that I'm inclined to remove that section b/c we already have/or can add the "contract us" part in other places.

**Comment by MathewBiddle** [comment]
I like having a contact us page. But, we do have all our contact info as a footer to the website....

**Comment by ocefpaf** [comment]
So we either expand it or remove it 😬

**Comment by ocefpaf** [comment]
I believe that PRs #196 and #195 cover this issue. Please reopen if I'm wrong.
