### ISSUE TITLE
Create a new release for gallery addition

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos_code_lab#192]
@ocefpaf You put a lot of work into adding that gallery! Lets make a new release! `v3.0.0` ? or `v2.1.0` ?

xref (among others):
* https://github.com/ioos/ioos_code_lab/pull/181
* https://github.com/ioos/ioos_code_lab/pull/174
* https://github.com/ioos/ioos_code_lab/issues/173

**Comment by ocefpaf** [comment]
I would do integer bumps here. Minor and micro bumps should mean small improvements and bug fixes, but adhering to SemVer in a gallery is odd to say the least.

**Comment by MathewBiddle** [comment]
I see. `v3.0.0` works for me. But, open to suggestions.

**Comment by ocefpaf** [comment]
> I see. `v3.0.0` works for me. But, open to suggestions.

If we were doing this for the first time, a CalVer would probably make more sense. However, b/c we already have some sort of SemVer out there, let's keep it in integer bumbos instead.

**Comment by MathewBiddle** [comment]
`CalVer` https://calver.org/ - new to me!

**Comment by MathewBiddle** [comment]
LMK when we're ready to tag and release.

**Comment by ocefpaf** [comment]
Done: https://github.com/ioos/ioos_code_lab/releases/tag/v3.0.0
