### ISSUE TITLE
New Python packages needed for CORA-HTF processing/analysis

### ISSUE THREAD

**Issue by conlin-matt** [ioos/ioos_code_lab#228]
@ocefpaf As Sagemaker is added to the IOOS sandbox to facilitate the deployment of a JupyterHub for processing of CORA data and implementation into the monthly Hight Tide Flooding model, some needed Python packages are not currently available in the environment files in /.binder.  The following Python packages are needed but do not appear to be listed in the environment files in /.binder:
- numpy
- scipy
- pandas
- intake
- dask
- scikit-learn
- holoviews

Is it possible for these to be installed?

**Comment by ocefpaf** [comment]
Only dask and intake are missing. I'll add them ASAP.

**Comment by conlin-matt** [comment]
Thank you! Apologies that I didn't notice those others were already there.

**Comment by ocefpaf** [comment]
> Thank you! Apologies that I didn't notice those others were already there.

Some are dependencies of dependencies, they won't appear explicitly. The only way to know for sure is by checking the lockfile or to create the image and try to import/list them. Let me know if this works for your workflow.

**Comment by conlin-matt** [comment]
Ah yes, got it. That should be just fine.
