### ISSUE TITLE
Configure Google Analytics for new url

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos_code_lab#3]
Not sure if GA is working correctly, I need to check the configuration we have for the current identifier. See https://github.com/ioos/notebooks_demos/issues/413

**Comment by ocefpaf** [comment]
It is in there https://github.com/ioos/ioos_code_lab/pull/1/commits/c02e06a7bb0ab92b766e9ab729750ecfc3af3412#diff-723280b4c2b8da08ef397d9545cb90d7f0db0fc5c30015b99857b3c2ee07112bR56

We need to check the dashboard to see if  it is collecting data.

**Comment by MathewBiddle** [comment]
Okay, I couldn't edit the existing stream so that we could reuse the GA ID. I created a new stream which has this 
```
google_analytics_id = G-6PET6017GE
```
Let's try that and if it works I can delete the old ID.

**Comment by MathewBiddle** [comment]
Thought I had the configuration wrong (https://github.com/ioos/ioos_code_lab/pull/6), but it's still not working. 

Maybe we need to update to most recent version? See: https://github.com/executablebooks/jupyter-book/issues/1300

**Comment by ocefpaf** [comment]
> Maybe we need to update to most recent version? See: [executablebooks/jupyter-book#1300](https://github.com/executablebooks/jupyter-book/issues/1300)

Can you check the dashboard again? The latest push is using the latest version of jupyterbook and has that fix.

**Comment by MathewBiddle** [comment]
still nothing... grrr

**Comment by ocefpaf** [comment]
We need this https://github.com/pydata/pydata-sphinx-theme/pull/439 but let me see if I can workaround it b/c that is no released yet.

**Comment by MathewBiddle** [comment]
Reopening because GA are still not working.

**Comment by ocefpaf** [comment]
New release today. See https://github.com/pydata/pydata-sphinx-theme/issues/479

It will be picked up by our CIs soon.

**Comment by ocefpaf** [comment]
Spoke too soon. Now we need a new release on sphinx-book-theme b/c it is pinned to an older pydata theme :-/

See https://github.com/executablebooks/sphinx-book-theme/blob/master/setup.py#L35

**Comment by ocefpaf** [comment]
xref.: https://github.com/executablebooks/sphinx-book-theme/pull/406

**Comment by MathewBiddle** [comment]
Any movement on this?
