### ISSUE TITLE
Move notebooks in PRs from the old site

### ISSUE THREAD

**Issue by ocefpaf** [ioos/ioos_code_lab#4]
- [x] https://github.com/ioos/notebooks_demos/pull/440
- [x] https://github.com/ioos/notebooks_demos/pull/406
- [x] https://github.com/ioos/notebooks_demos/pull/398
- [x] https://github.com/ioos/notebooks_demos/pull/393
- [x] https://github.com/ioos/notebooks_demos/pull/390
- [x] https://github.com/ioos/notebooks_demos/pull/370
- [x] https://github.com/ioos/notebooks_demos/pull/362
- [x] https://github.com/ioos/notebooks_demos/pull/356
- [x] https://github.com/ioos/notebooks_demos/pull/347

**Comment by MathewBiddle** [comment]
@ocefpaf I think I've moved all of the notebooks over. https://github.com/ioos/ioos_code_lab/pulls?q=is%3Apr+is%3Adraft+

I do want to xref to the appropriate tickets/PR in notebooks_demos, so I'll be working through that next.

**Comment by MathewBiddle** [comment]
so I've cross-referenced, in case anyone wants to go back to the conversation in notebooks_demo. I've closed all the related PRs in that repo as well. 

Closing.
