### ISSUE TITLE
Query IOOS CKAN API for specific free text variable

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos_code_lab#47]
* xref: https://github.com/ioos/notebooks_demos/issues/405

@mwengren has some solid examples here: https://github.com/mwengren/notebooks-dev/tree/master/ioos_ckan_catalog

Lets make a plan for adding them to the code lab.

**Comment by MathewBiddle** [comment]
Can we expand this notebook to not only search for stations, but bring back all of the appropriate data? Maybe return a netCDF/csv file?

I think the table @mwengren creates at the end of this notebook [1] has the endpoints (ERDDAP/THREDDS), but I'm not 100% on that. 

[1] https://nbviewer.org/github/mwengren/notebooks-dev/blob/master/ioos_ckan_catalog/ioos_catalog_ckanapi_standard_name_query.ipynb

@ocefpaf any ideas?

**Comment by MathewBiddle** [comment]
Let's append to that notebook using cf_xarray's `.cf[]` to search for those standard names, then cf_xarray `.cf['latitude']` and `.cf['longitude']` to pull out the coordinates and make a map.

**Comment by MathewBiddle** [comment]
Checkout `IN [11]:` in this notebook [1] where I iteratively search through a THREDDS catalog to find files containing one of a list of standard_names. Then, I pull out the lat/lons to make a map.

[1] https://github.com/MathewBiddle/sandbox/blob/main/IOOS_data_at_NCEI.ipynb

**Comment by MathewBiddle** [comment]
@ocefpaf did you start tinkering with this notebook?

If not, I think we can use the notebook @mwengren started, skipping the widgets and panel pieces.

I would be interested in using this to search only across RAs too.

**Comment by ocefpaf** [comment]
> @ocefpaf did you start tinkering with this notebook?

Yes but I lost my progress. I cannot find it :-/ (And I teach reproducible research and GitHub...)

> If not, I think we can use the notebook @mwengren started, skipping the widgets and panel pieces.

That was my starting point. I'll start over and send a PR here.

> I would be interested in using this to search only across RAs too.

:+1:

**Comment by MathewBiddle** [comment]
@mwengren I tried to run your notebook but only 6 datasets are showing up in the catalog.

```python
>> from ckanapi import RemoteCKAN
>> ua = 'ckanapiioos/1.0 (+https://ioos.us/)'
>> ioos_catalog = RemoteCKAN('https://data.ioos.us', user_agent=ua)
>> ioos_catalog.action.package_search()['count']
6
```

**Comment by MathewBiddle** [comment]
I started, yet another, notebook to do something similar: https://github.com/MathewBiddle/sandbox/blob/main/notebooks/CKAN_API_Query.ipynb

**Comment by MathewBiddle** [comment]
I never wrote down the purpose of this issue. Below is a high level scoping of the notebook.

**Programming Language**
What programming language(s) will be used in the example?
* Python

**Module/Software/IOOS data service?**
Is it focused on a particular module/software or an IOOS data service?
* IOOS Catalog https://data.ioos.us/
* NCEI Geoportal API https://www.ncei.noaa.gov/metadata/geoportal/#aboutPanel

**Module/Software/IOOS data service?**
Can you provide a minimum example of the expected code and results in a notebook?
* Query NCEI Geoportal for datasets https://github.com/MathewBiddle/sandbox/blob/main/IOOS_data_at_NCEI.ipynb
* IOOS Catalog query https://github.com/MathewBiddle/sandbox/blob/main/notebooks/CKAN_API_Query.ipynb
* (bonus) IOOS Sensor Map query https://github.com/MathewBiddle/sandbox/blob/main/notebooks/DRAFT_sensor_map_query.ipynb

**Provide a description.**
Please provide a detailed description of the suggested example below.
* Explore ways to better connect regional observations (moorings/fixed platforms) into NCEI activities like the Dissolved Oxygen (DO) Indicator for the NOAA Ecosystem Indicator portal. Essentially determine a way to show what the RAs have vs what is in the NCEI archive from the RAs. This will help identify future assets to archive at NCEI. We will need to highlight our assumptions at the top of the notebook (eg. RA assets are discoverable via IOOS Catalog).

**Comment by MathewBiddle** [comment]
I think this would be a good one to publish here: https://github.com/MathewBiddle/sandbox/blob/main/notebooks/CKAN_API_Query.ipynb

I highlights the use of our IOOS Data Catalog CKAN endpoint and shows how you can grab source data from various ERDDAP endpoints.

@ocefpaf let me know if you agree and I can start merging it here.

**Comment by ocefpaf** [comment]
> @ocefpaf let me know if you agree and I can start merging it here.

100% agree. We are lacking a IOOS Data Catalog CKAN example for years now. That one seems great!
