### ISSUE TITLE
Supporting RMarkdown?

### ISSUE THREAD

**Issue by emiliom** [ioos/ioos_code_lab#60]
Hi @MathewBiddle. I'll ask here, for lack of a better alternative other than email or Slack. The IOOS CodeLab has Jupyter notebooks in R. Has the thought or need for supporting Rmarkdown ever come up? Specifically, how do you best support contributors who do nothing but R, for whom using a Jupyter notebook to do R might be an annoying hurdle? I've been pondering that possibility, but I'm not aware of good options that can make both Jupyter+Python and R-ecosystem people happy. The NASA-Openscapes group used [quarto](https://quarto.org/) to do this for their [Cloud hackathon](https://nasa-openscapes.github.io/2021-Cloud-Hackathon/), but I haven't wrapped my head around its workflow yet. In my own ideal world, JupyterBook would support RMarkdown notebooks, but I haven't found solutions that implement this.

**Comment by ocefpaf** [comment]
We use JupyterBook and they have limited support for RMarkdown with jupytext:

https://jupyterbook.org/file-types/jupytext.html#using-jupytext

I would not use it at the moment. My tests gave me some bad results, poor display of widgets, etc. It may have improved since I tested it but I'm not sure.

**Comment by emiliom** [comment]
Thanks for both the pointer and the warning.

I'm reading more about [quarto](https://quarto.org/) and NASA-Openscapes's workflow. I doubt I'll start using it, but it's an interesting contrast and has helpful ideas. See their [Contributing/quarto text](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/#quarto), and the [Initial setup](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/setup.html) and [Workflow](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/workflow.html) pages.

**Comment by MathewBiddle** [comment]
@emiliom to answer the first question, no it hasn't come up. Yet! But seems worth thinking about...

I agree with @ocefpaf's comments above. Another option could be to go the other way using R bookdown to run Python code [1].

[1] https://bookdown.org/yihui/rmarkdown-cookbook/eng-python.html

But, after deploying this guide [2] I can say that bookdown is a lot more confusing to get running than Jupyter notebooks increasing the barrier to contributions.

[2] https://ioos.github.io/bio_data_guide/

Seems like there isn't a good solution yet, but definitely something to monitor as new tech comes out.

**Comment by emiliom** [comment]
Thanks!
