### ISSUE TITLE
Intro to zarr notebook

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos_code_lab#93]
- [ ] What is language(s) for used in the example?
Python
- [ ] Is it focused on a particular module/software or an IOOS data service?
Zarr
- [ ] Can you provide a minimum example of the expected code and results in a notebook?
I think @ocefpaf has some

Please provide a detailed description of the suggested example below:
We should add an introduction to zarr notebook. Some things to include:
* Translating netCDF to zarr
* Creating zarr
* Working with zarr

**Comment by ocefpaf** [comment]
I probably have m that already, just need to aggregate into a single notebook and create a story.

**Comment by ocefpaf** [comment]
xref.: #98

**Comment by ocefpaf** [comment]
Done in #131
